name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.7' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run vectorhub integration tests
        env:
          TEST_PROJECT: ${{ secrets.TEST_US_PROJECT }}
          TEST_API_KEY: ${{ secrets.TEST_US_API_KEY }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install -e .[tests]
          python -m pip install pytest-sugar pytest-rerunfailures pytest-xdist
          python -m pip install vectorhub[clip,encoders-text-tfhub]
          python -m pytest test_integrations/vectorhub/ --cov-fail-under=1