
name: Unit Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.7' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        include:
          - os: ubuntu-latest
            # path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Cache pip
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ matrix.path }}
      #     key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements-dev.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ env.pythonLocation }}-pip-
      #       ${{ runner.os }}-${{ env.pythonLocation }}-
      - uses: nick-fields/retry@v2
        env:
          # TEST_PROJECT: ${{ secrets.TEST_PROJECT }}
          # TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_PROJECT: ${{ secrets.TEST_US_PROJECT }}
          TEST_API_KEY: ${{ secrets.TEST_US_API_KEY }}
          TEST_TOKEN: ${{ secrets.TEST_US_TOKEN }}
          DEBUG_REQUESTS: "FALSE"
        with:
          max_attempts: 5
          timeout_minutes: 15
          retry_on: error
          command: |
            python -c "import sys; print(sys.version)"
            python -m pip install --upgrade pip
            python -m pip install -e .[tests]
            python -m pip install pytest-sugar pytest-cov pytest-rerunfailures pytest-xdist sentence-splitter sentence-transformers
            python -m pytest tests/unit --cov-config=coverage/coverage.cfg --cov=relevanceai -vv -rs -x -n auto tests --cov-fail-under=20  --ignore=relevanceai/operations_new/
